#Application
server:
  port: ${PORT:8080}

# Spring
spring:
  application:
    name: template-service-3.0
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PWD:Devdev123}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:postgres}?useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

#Open API v3
app:
  descr: 'Template Service 3.0'
  ver: '1.0.0'

springdoc:
  api-docs:
    path: /api-docs

management:
  server:
    port: 9090

# Test OpenFeign
cif:
  apis: http://localhost:20210/customer/cif

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: full
        readTimeout: 5000
#Logging
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error
#Pagination
paging:
  size: 30
  page: 0
  max-size: 500